# Markdown lint configuration
default: true

# MD013: Line length
MD013:
  line_length: 120
  heading_line_length: 80
  code_block_line_length: 120
  code_blocks: false
  tables: false
  headings: true

# MD033: Inline HTML
MD033:
  allowed_elements:
    - br
    - details
    - summary
    - img
    - sup
    - sub

# MD041: First line in file should be a top level heading
MD041: false
